/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lqhakdoibcltgyryjpvq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxaGFrZG9pYmNsdGd5cnlqcHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MjcwNjEsImV4cCI6MjA3ODQwMzA2MX0.zEbvq-IvhU4rD1D5lWFJdncmPD7lqU0-5P7UhTrArbQ"